import React from 'react'

// Apple Podcasts show player, as generated by Apple Marketing Tools:
// https://toolbox.marketingtools.apple.com/en-us/apple-podcasts/us/podcast/1435008302
// The "large" player is 16:9 up to 660px wide and adapts its own layout on narrow screens.
const EMBED_URL =
  'https://embed.podcasts.apple.com/us/podcast/the-golden-hurricast/id1435008302' +
  '?itscg=30200&itsct=podcast_box_player&ls=1&mttnsubad=1435008302&theme=light&size=large'

const ApplePodcastsEmbed = () => (
  <iframe
    title='The Golden Hurricast on Apple Podcasts'
    src={EMBED_URL}
    className='apple-podcasts-embed'
    loading='lazy'
    sandbox='allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation-by-user-activation'
    allow='autoplay *; encrypted-media *; clipboard-write'
  />
)

export default ApplePodcastsEmbed
