import type { Handle } from '@sveltejs/kit/hooks';

/** The same security headers `_headers` applies to static files (see that file). */
const SECURITY_HEADERS = {
	'strict-transport-security': 'max-age=31536000; includeSubDomains',
	'x-content-type-options': 'nosniff',
	'referrer-policy': 'strict-origin-when-cross-origin',
	'permissions-policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
	'cross-origin-opener-policy': 'same-origin',
	'x-frame-options': 'DENY'
};

// Domain aliases go to the primary domain. `_redirects` does the same for static files;
// paths without one reach this function first.
const PRIMARY_ORIGIN = 'https://www.thegoldenhurricast.com';
const ALIAS_HOSTS = new Set(['www.goldenhurricast.com', 'thegoldenhurricast.netlify.com']);

// URLs from the Gatsby site that still have an equivalent. Its other files (header logo,
// brand icons, badges, the About photo) were page decoration with no counterpart: they 404.
const OLD_PATHS = new Map([
	['/merch-success', '/merch/'],
	['/merch-success/', '/merch/'],
	['/patreon.png', '/blog_images/patreon/patreon-tiers.png'],
	// WebP copies of icons that are now PNG only.
	...[
		'android-chrome-192x192',
		'android-chrome-512x512',
		'apple-touch-icon',
		'favicon-16x16',
		'favicon-32x32',
		'logo-300px'
	].map((name) => [`/${name}.webp`, `/${name}.png`] as const)
]);

function legacyRedirect(url: URL): string | undefined {
	if (ALIAS_HOSTS.has(url.host)) return `${PRIMARY_ORIGIN}${url.pathname}${url.search}`;
	// Home-screen icons generated by gatsby-plugin-manifest (/icons/icon-48x48.png, …).
	if (/^\/icons\/icon-\d+x\d+\.png$/.test(url.pathname)) return '/apple-touch-icon.png';
	return OLD_PATHS.get(url.pathname);
}

export const handle: Handle = async ({ event, resolve }) => {
	const location = legacyRedirect(event.url);
	const response = location
		? new Response(null, { status: 301, headers: { location } })
		: await resolve(event);
	for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
		if (!response.headers.has(name)) response.headers.set(name, value);
	}
	return response;
};
