<!--
	@component
	Apple Podcasts show player, as generated by Apple Marketing Tools
	(https://toolbox.marketingtools.apple.com/en-us/apple-podcasts/us/podcast/1435008302).

	Apple's player loads ~600 KB of third-party JavaScript and artwork, so the page renders a
	lightweight stand-in and only adds the player once the page has finished loading and the
	browser is idle. The player fades in over the stand-in when it's ready. Without JavaScript,
	the stand-in is simply a link to the show on Apple Podcasts.

	The "large" player is 16:9 up to 660px wide; the minimum height keeps its "Latest Episode"
	button visible on small phones.
-->
<script lang="ts">
	import logo from '#lib/assets/logo-navbar-white.png?enhanced';
	import { LINKS, SITE } from '#lib/site.js';

	/** The player's iframe is in the page (it may still be loading). */
	let mounted = $state(false);
	/** The player has loaded and covers the stand-in. */
	let ready = $state(false);

	$effect(() => {
		let cancel: (() => void) | undefined;
		const mount = () => {
			const show = () => (mounted = true);
			if ('requestIdleCallback' in window) {
				const id = requestIdleCallback(show, { timeout: 2000 });
				cancel = () => cancelIdleCallback(id);
			} else {
				const id = setTimeout(show, 200);
				cancel = () => clearTimeout(id);
			}
		};

		// Never compete with the page's own loading.
		if (document.readyState === 'complete') mount();
		else addEventListener('load', mount, { once: true });

		return () => {
			removeEventListener('load', mount);
			cancel?.();
		};
	});
</script>

<div
	class="relative mx-auto aspect-video min-h-[175px] w-full max-w-[660px] overflow-hidden rounded-xl bg-surface"
>
	<a
		href={LINKS.applePodcasts}
		target="_blank"
		rel="noopener noreferrer"
		inert={ready}
		class="group flex size-full items-center gap-5 p-5 text-ink no-underline hover:text-ink sm:gap-6 sm:p-8"
	>
		<!-- The wrapper, not the image, is the flex item, so the artwork never gets squeezed. -->
		<span
			class="size-24 shrink-0 overflow-hidden rounded-lg bg-white shadow-photo sm:size-40 [&_img]:size-full"
		>
			<enhanced:img src={logo} alt="" sizes="(min-width: 40rem) 160px, 96px" loading="lazy" />
		</span>
		<span class="flex min-w-0 flex-col gap-1">
			<span class="text-sm text-muted">Apple Podcasts</span>
			<span class="text-xl font-bold">{SITE.name}</span>
			<span class="hidden text-muted sm:block">
				A weekly podcast covering Tulsa Golden Hurricane athletics.
			</span>
			<span
				class="mt-2 inline-flex items-center gap-2 self-start rounded-full bg-ink px-4 py-2 text-sm text-white group-hover:bg-black"
			>
				<svg viewBox="0 0 24 24" class="size-4" aria-hidden="true">
					<path d="M8 5v14l11-7z" fill="currentColor" />
				</svg>
				Listen on Apple Podcasts
			</span>
		</span>
	</a>

	{#if mounted}
		<iframe
			title="{SITE.name} on Apple Podcasts"
			src={LINKS.applePodcastsEmbed}
			loading="lazy"
			sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation-by-user-activation"
			allow="autoplay *; encrypted-media *; clipboard-write"
			onload={() => (ready = true)}
			class={[
				'absolute inset-0 size-full border-0 bg-surface transition-opacity duration-300 motion-reduce:transition-none',
				!ready && 'pointer-events-none opacity-0'
			]}
		></iframe>
	{/if}
</div>
