<!--
	@component
	Apple Podcasts show player, as generated by Apple Marketing Tools
	(https://toolbox.marketingtools.apple.com/en-us/apple-podcasts/us/podcast/1435008302).

	Apple's player loads ~600 KB of third-party JavaScript and artwork, so the page shows a
	lightweight stand-in until a visitor asks for the player. Without JavaScript, the stand-in
	is simply a link to the show on Apple Podcasts.

	The "large" player is 16:9 up to 660px wide; the minimum height keeps its "Latest Episode"
	button visible on small phones.
-->
<script lang="ts">
	import logo from '#lib/assets/logo-navbar-white.png?enhanced';
	import { LINKS, SITE } from '#lib/site.js';

	let loaded = $state(false);
</script>

<div
	class="mx-auto aspect-video min-h-[175px] w-full max-w-[660px] overflow-hidden rounded-xl bg-surface"
>
	{#if loaded}
		<iframe
			title="{SITE.name} on Apple Podcasts"
			src={LINKS.applePodcastsEmbed}
			sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation-by-user-activation"
			allow="autoplay *; encrypted-media *; clipboard-write"
			class="block size-full border-0 bg-transparent"
		></iframe>
	{:else}
		<a
			href={LINKS.applePodcasts}
			target="_blank"
			rel="noopener noreferrer"
			onclick={(event) => {
				event.preventDefault();
				loaded = true;
			}}
			class="group flex size-full items-center gap-5 p-5 text-ink no-underline hover:text-ink sm:gap-6 sm:p-8"
		>
			<enhanced:img
				src={logo}
				alt=""
				sizes="(min-width: 40rem) 160px, 96px"
				loading="lazy"
				class="size-24 shrink-0 rounded-lg bg-white shadow-photo sm:size-40"
			/>
			<span class="flex flex-col gap-1">
				<span class="text-sm text-muted">Apple Podcasts</span>
				<span class="text-xl font-bold">{SITE.name}</span>
				<span class="hidden text-muted sm:block">
					A weekly podcast covering Tulsa Golden Hurricane athletics.
				</span>
				<span
					class="mt-2 inline-flex items-center gap-2 self-start rounded-full bg-ink px-4 py-2 text-sm text-white group-hover:bg-black"
				>
					<svg viewBox="0 0 24 24" class="size-4" aria-hidden="true">
						<path d="M8 5v14l11-7z" fill="currentColor" />
					</svg>
					Load the player
				</span>
			</span>
		</a>
	{/if}
</div>
